PUT localhost:9200/_opendistro/_rollup/jobs/example
Content-Type: application/json

{
  "rollup": {
    "enabled": true,
    "schedule": {
      "interval": {
        "period": 1,
        "unit": "Minutes",
        "start_time": {{$timestamp}}
      }
    },
    "last_updated_time": {{$timestamp}},
    "description": "An exmaple policy that rolls up the sample ecommerce data",
    "source_index": "kibana_sample_data_ecommerce",
    "target_index": "rollup-test-index",
    "page_size": 100,
    "delay": 0,
    "dimensions": [
      {
        "date_histogram": {
          "source_field": "order_date",
          "fixed_interval": "1h",
          "timezone": "America/Los_Angeles"
        }
      },
      {
        "terms": {
          "source_field": "geoip.city_name"
        }
      }
    ],
    "metrics": [
      {
        "source_field": "taxless_total_price",
        "metrics": [{ "sum":  {} }]
      }
    ]
  }
}

###
POST localhost:9200/rollup-test-index/_search
###
GET localhost:9200/_cat/indices

###
POST localhost:9200/kibana_sample_data_ecommerce/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "city": {
      "terms": {
        "field": "geoip.city_name",
        "size": 5,
        "order": {"total_sales": "desc"}
      },
      "aggs": {
        "total_sales": {
          "sum": {
            "field": "taxless_total_price"
          }
        }
      }
    }
  }
}

###
POST localhost:9200/rollup-test-index/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "city": {
      "terms": {
        "field": "geoip.city_name",
        "size": 5,
        "order": {"total_sales": "desc"}
      },
      "aggs": {
        "total_sales": {
          "sum": {
            "field": "taxless_total_price"
          }
        }
      }
    }
  }
}
###
DELETE localhost:9200/rollup-test-index
###
PUT localhost:9200/rollup-test-index
Content-Type: application/json

{
  "mappings": {
    "_meta" : {
      "schema_version": 1,
      "rollups": {
        "something": {}
      }
    },
    "dynamic_templates" : [
      {
        "strings" : {
          "match_mapping_type" : "string",
          "mapping" : {
            "type" : "keyword"
          }
        }
      },
      {
        "date_histograms" : {
          "path_match" : "*.date_histogram.*",
          "mapping" : {
            "type" : "date"
          }
        }
      }
    ]
  },
  "settings": {
    "index.opendistro.rollup_index": true
  }
}