name: unique name
on:
  issue_comment:
    branches:
      - master
      - opendistro-*

jobs:
  stuff:
    strategy:
      matrix:
        java: [12]
    # Job name
    name: doing things ${{ matrix.java }}
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: This is a test
        uses: actions/dbbaughe-testing@v1
